AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.5

Layout/IndentationStyle:
  IndentationWidth: 1
  EnforcedStyle: tabs

Layout/IndentationWidth:
  Width: 1

Layout/EndOfLine:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/Base64encoding.rb"
    - "spec/Base64encoding_spec.rb"
